sudo: required

services:
  - docker

language: node_js
node_js:
  - '10'

cache:
  npm: true
  directories:
  - node_modules

install:
  - npx npm install

script:
  - npx npm run dev:lint

notifications:
  slack: ambrosus:ybmTQyso2XmAp6SM9NQPhdl2
