version: "3"
services:
  db:
    image: mongo:latest
    ports:
      - '27017:27017'
    container_name: "db"

  parity:
    image: parity/parity:nightly
    command: ['--chain', 'dev', '--unsafe-expose']
    ports:
      - '8545:8545'
